# This file was generated by GoReleaser. DO NOT EDIT.
cask "rolle-cli" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "2cace78228b11da3484719c80faec31afe67a408b64902945c8104a865a40cd3"
      url "https://github.com/nateships/rolle/releases/download/v#{version}/rolle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bad78cb36fd13800ba6f13089440023cb42135a9e60c207fe622bff29e56c63f"
      url "https://github.com/nateships/rolle/releases/download/v#{version}/rolle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "912733bb47bf17b548c5afb460289cdb25d982da742a14a964119e5ef373c1c0"
      url "https://github.com/nateships/rolle/releases/download/v#{version}/rolle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c1c459966a126febc36f703ea344422e447f86794f6cc2bcfaf88b2077d1a5c2"
      url "https://github.com/nateships/rolle/releases/download/v#{version}/rolle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rolle-cli"
  desc "Assume any role, any cloud"
  homepage "https://getrolle.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rolle"

  generate_completions_from_executable "rolle", "completion",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
